### ISSUE TITLE
Need explanation about PostRepository.

### ISSUE THREAD

**Issue by zeyser** [fesor/api-example#4]
Can you explain me? [Here](https://github.com/fesor/api-example/blob/master/app/Posts/Model/PostRepository.php#L18) you set your new post to persist into entityManager and where you flush it? Where we actually save it?

**Comment by fesor** [comment]
In controller, because it's the only place which knows where's boundaries of our business transaction. If you have command bus - one of it's middlewares could perform flush for you. If you wrap every use case into separate service - some sort of decorator for this kind of services could be used (sort of AOP). 

Repositories should act as in-memory collections, they are not table gateways. And there should be only one repository per aggregate (for aggregate root only).

Sometime you will want to split operation into several logical transactions, but I use domain events and sagas for this kind of things.

**Comment by zeyser** [comment]
>  but I use domain events and sagas for this kind of thing. 

Perhaps you can suggest one of your github repositories (or you know the other) with this approach? I need to see how to implement such kind of things.
Thanks for your descriptive answer!
P.S. Sorry, if this question out of the scope of this repo

**Comment by fesor** [comment]
I currently not having such an example (mostly because I can't think of an simple example to demonstrate it and i don't have time for more sophisticated examples).
